...
void testClass1 :: testMethod()
{
   throw "my exception!";  // BAD
}
...
void testClass3 :: testMethod()
{
  try { throw "my exception!"; } // GOOD
  catch (...) { clean(); }
}
...
std::runtime_error("msg error"); // BAD
...
throw std::runtime_error("msg error"); // GOOD
...
